version: '3'

services:
   db:
      image: postgres:10.6
      container_name: rails_survey_db
   web:
      build: .
      image: rails_survey/web:latest
      container_name: rails_survey-web
      command: bash -c "bundle exec rails db:create db:migrate db:seed && puma"
      depends_on:
         - db
      ports:
         - 8080:8080
      volumes:
         - ./:/app
         - /app/node_modules